### PR TITLE
Replace \r + " chars in addition in some env variables

### LINKED ISSUE #237: Build is failing because of incorrect definition of long description
Hi,

we still have the issue that some long descriptions will fail the complete build. Please see the following output
```
10:41:28 [resources] $ /home/ubuntu/.ant/bin/ant -file build.xml -DghprbActualCommitAuthorEmail=ivan.senic@novatec-gmbh.de -DghprbTriggerAuthorLogin= -DghprbGhRepository=inspectIT/inspectIT -DghprbTargetBranch=master -DghprbPullId=9 -DghprbCredentialsId=f9564afd-e9e5-4935-8957-e44dace783d8 -DghprbAuthorRepoGitUrl=https://github.com/ivansenic/inspectIT.git -DghprbTriggerAuthor= -DghprbPullAuthorEmail= -DghprbPullLink=https://github.com/inspectIT/inspectIT/pull/9 -Dsha1=origin/pr/9/merge -DghprbPullAuthorLoginMention=@ivansenic "-DghprbPullDescription=GitHub pull request #9 of commit 75525ce2ef82cd2d493d2f0cb96c19a2b13a92b1, no merge conflicts." -DghprbActualCommit=75525ce2ef82cd2d493d2f0cb96c19a2b13a92b1 -DghprbPullAuthorLogin=ivansenic -DghprbSourceBranch=INSPECTIT-1938 "-DghprbActualCommitAuthor=Ivan Senic" -DghprbTriggerAuthorLoginMention= '-DghprbPullLongDescription=~~Note that commons-net is already included in the THIRDPARTYLICENSE.txt~~
\n
\n_As we moved to github API Commons Net are removed and I added Gson as new dependency._
\n
\n<!-- Reviewable:start -->
\n[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/9)
\n<!-- Reviewable:end -->
\n' -DghprbTriggerAuthorEmail= -DGIT_BRANCH=INSPECTIT-1938 "-DghprbPullTitle=INSPECTIT-1938: (Auto-)Check for new version available in UI" -DghprbCommentBody=null clean
10:41:28 Buildfile: /home/ubuntu/jenkins/workspace/inspectIT - Pull Request Check/Commons/resources/build.xml
10:41:29 
10:41:29 BUILD FAILED
10:41:29 Target "on" does not exist in the project "inspectIT - Commons". 
10:41:29 
10:41:29 Total time: 0 seconds
10:41:29 Build step 'Invoke Ant' marked build as failure
```

Is there somehow an easy fix for this? Because of this problem, we have to revert to a quite old version of the plugin. Can we maybe just ignore that long description completely so that it will not even appear in the execution?

Cheers,
Patrice

### PR DESCRIPTION
**Pull request by pbouillet**
fixes #237

### CODE REVIEW

File: src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java [hunk 1]
```diff
@@ -302,7 +302,10 @@ public void run() {
         // one isn't there
         return this.job.scheduleBuild2(job.getQuietPeriod(), cause, new ParametersAction(values), findPreviousBuildForPullId(pullIdPv));
     }
-    
+
+    private String escapeText(String text) {
+        return text.replace("\n", "\\n").replace("\r", "\\r").replace("\"", "\\\"");
```
Comment (DavidTanner) [inline src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java]: Should the \ be replaced first?  Otherwise you would end up with: `\n` -> `\\n` -> `\\\\\\n`

Comment (pbouillet) [inline src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java]: I'm not replacing a \, I'm replacing a " with a \". It just looks weird in the Java syntax itself as these characters need to be replaced for the replacement, too. And with this replacement, our job now works again fine.

Comment (DavidTanner) [inline src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java]: I missed the ", sorry.
