### PR TITLE
Fixing NPE and non-sensical behavior of the GHPRB

### LINKED ISSUE #158: NPEs in GHPRB Merge
```
2015-08-16 03:41:46.917: java.lang.NullPointerException
2015-08-16 03:41:46.917: 	at org.jenkinsci.plugins.ghprb.GhprbPullRequestMerge.perform(GhprbPullRequestMerge.java:151)
2015-08-16 03:41:46.917: 	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
2015-08-16 03:41:46.917: 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:776)
2015-08-16 03:41:46.917: 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
2015-08-16 03:41:46.917: 	at hudson.model.Build$BuildExecution.post2(Build.java:183)
2015-08-16 03:41:46.917: 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
2015-08-16 03:41:46.917: 	at hudson.model.Run.execute(Run.java:1763)
2015-08-16 03:41:46.917: 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
2015-08-16 03:41:46.917: 	at hudson.model.ResourceController.execute(ResourceController.java:98)
2015-08-16 03:41:46.917: 	at hudson.model.Executor.run(Executor.java:381)
2015-08-16 03:41:46.918: Build step 'Github Pull Request Merger' marked build as failure
```

The culprit is [here](https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java#L151): `triggerSender` can be null.

### PR DESCRIPTION
**Pull request by arcivanov**
1. Fix NPEs where `triggerSender` is not available
2. Infer intent to merge based on comment trigger
3. If merge can only triggered by comment and there is no comment, there is no intent to merge, therefore do not fail or check other conditions
4. Do not post comments about commentors not being Admins etc if build is triggered by automation

connected to #158, fixes #158

### CODE REVIEW

**Comment by arcivanov** [comment]
retest this please

File: src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMergeTest.java [hunk 1]
```diff
@@ -282,7 +282,7 @@ public void testTriggerMerge() throws Exception {
         assertThat(merger.perform(build, null, listener)).isEqualTo(true);
 
         setupConditions(adminLogin, committerName, committerEmail, nonTriggerPhrase);
-        assertThat(merger.perform(build, null, listener)).isEqualTo(false);
+        assertThat(merger.perform(build, null, listener)).isEqualTo(true);
```
Comment (DavidTanner) [inline src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMergeTest.java]: The intentions here are to verify that the merge didn't happen.  How would you still verify that the merge wasn't attempted?

Comment (arcivanov) [inline src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMergeTest.java]: I can encapsulate the "is there intention to merge?" into a separate method test that and then compare with "did merge?". The problem with checking `merger.perform()` return value is that it API documents it along the lines of "false if should not proceed to other publishers".
Could also check for build status changes (i.e. FAILURE) to make sure the build fails when it should, regardless of `perform` return value.

**Comment by arcivanov** [comment]
@DavidTanner 

I have a bigger question - does `isOnlyTriggerPhrase` make sense at all? If it is set, then trigger phrase ONLY triggers an attempt to merge regardless of the cause for a build (e.g. commit hook). 

But if it is not set, then EVERY build, regardless of trigger cause, becomes an attempt to merge, doesn't it? Then "only admin can merge" becomes nonsensical, because unless you are an admin behind the commit that triggered a hook, your build will fail. And if "can't merge own code" is turned on, then all builds that are not triggered by a phrase will fail unless you commit the code that isn't yours.

**Comment by DavidTanner** [comment]
@arcivanov The requirements that I had when adding the functionality were to follow some government rules.  The trigger phrase was so that not every pull request would be run, and I am not sure that it is necessary really.
1. Only certain people were to be allowed to merge code into master.
2. A person couldn't merge their own code.

**Comment by arcivanov** [comment]
@DavidTanner
> The trigger phrase was so that not every pull request would be run,

But I think that's the point I'm trying to make if `isOnlyTriggerPhrase` is __false__ then every build, no matter the trigger, will result in an attempt to merge. But the build will __always fail__ if your commit has triggered a hook-based build and you're disallowed to merge your own code or only admins can merge and you're not an admin. Moreover, it can also cause unintentional merges on the first PR commit, which is hardly desirable.

Should we obsolete `isOnlyTriggerPhrase` and just assume that the trigger phrase is __always__ needed to initiate a merge?

**Comment by arcivanov** [comment]
@DavidTanner bump?

File: src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java [hunk 2]
```diff
@@ -37,34 +37,38 @@
...
-        this.onlyTriggerPhrase = onlyTriggerPhrase;
         this.onlyAdminsMerge = onlyAdminsMerge;
         this.disallowOwnCode = disallowOwnCode;
         this.failOnNonMerge = failOnNonMerge;
         this.deleteOnMerge = deleteOnMerge;
     }
 
-    public String getMergeComment() {
-        return mergeComment;
+    public GhprbPullRequestMerge(
```
Comment (DavidTanner) [inline src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java]: Why leave this constructor?

File: src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java [hunk 3]
```diff
@@ -137,44 +141,58 @@ public boolean perform(AbstractBuild<?, ?> build, Launcher launcher, final Build
...
         }
 
-        if (isDisallowOwnCode() && (triggerSender == null || isOwnCode(pr, triggerSender) )) {
-            merge = false;
-            logger.println("The commentor is also one of the contributors.");
-            commentOnRequest(String.format("Code not merged because %s has committed code in the request.", triggerSender.getName()));
+        // If there is no intention to merge there is no point checking
+        if (intendToMerge && isDisallowOwnCode() && (triggerSender == null || isOwnCode(pr, triggerSender))) {
+            canMerge = false;
+            if (triggerSender != null) {
```
Comment (DavidTanner) [inline src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java]: I would want to know that the trigger sender was null also if this failed.

File: src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java [hunk 4]
```diff
@@ -137,44 +141,58 @@ public boolean perform(AbstractBuild<?, ?> build, Launcher launcher, final Build
...
+        }
 
-            commentOnRequest(String.format("Please comment with '%s' to automerge this request", trigger.getTriggerPhrase()));
+        // If there is no intention to merge there is no point checking
+        if (intendToMerge && isOnlyAdminsMerge() && (triggerSender == null || !helper.isAdmin(triggerSender))) {
+            canMerge = false;
+            logger.println("Only admins can merge this pull request, "
+                    + (triggerSender != null ? triggerSender.getLogin() + " is not an admin"
+                            : " and build was triggered via automation") + ".");
+            if (triggerSender != null) {
```
Comment (DavidTanner) [inline src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java]: I would want to know that the build failed because the triggerSender was null.  That would tell me there was a configuration issue, or that the build was triggered by something else.

**Comment by DavidTanner** [comment]
I think that I thought of this step more like if the build succeeds to this point, it is expected to be run.

File: src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java (hunk 2 above)
Comment (arcivanov) [inline src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java]: Backwards compatibility with existing configurations.

File: src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java (hunk 4 above)
Comment (arcivanov) [inline src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java]: The build wouldn't fail if the `triggerSender` is `null`. The build would succeed (all other things being equal) but there would not be an attempt to merge. This code can only be reached in the unlikely situation that a trigger comment was posted by an unauthenticated automation which I'm not even sure is possible.

File: src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java (hunk 3 above)
Comment (arcivanov) [inline src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java]: Why? And how would you want to know?

**Comment by arcivanov** [comment]
Here's the scenario I'm targeting:

1. Developer without commit privileges submits a PR.
2. Admin, without commit privileges reviews the PR.
3. Admin and developer go back and forth with developer submitting additional commits and PR being built multiple times by hooks, commands or cron check triggers without any intent to merge and admin posting review comments.
4. After all work is done and everyone is satisfied, the Admin issues a merge trigger comment, automation builds the PR one last time and merges it into its target branch on success.

**Comment by arcivanov** [comment]
@DavidTanner gentle bump
